AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler
      Runtime: go1.x
      Tracing: Active
      CodeUri: ./dist/handler.zip
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
